/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IwsEventsFinder {
    }
    interface IwsGetData {
    }
}
declare global {
    interface HTMLIwsEventsFinderElement extends Components.IwsEventsFinder, HTMLStencilElement {
    }
    var HTMLIwsEventsFinderElement: {
        prototype: HTMLIwsEventsFinderElement;
        new (): HTMLIwsEventsFinderElement;
    };
    interface HTMLIwsGetDataElement extends Components.IwsGetData, HTMLStencilElement {
    }
    var HTMLIwsGetDataElement: {
        prototype: HTMLIwsGetDataElement;
        new (): HTMLIwsGetDataElement;
    };
    interface HTMLElementTagNameMap {
        "iws-events-finder": HTMLIwsEventsFinderElement;
        "iws-get-data": HTMLIwsGetDataElement;
    }
}
declare namespace LocalJSX {
    interface IwsEventsFinder {
        "onIwsConferenceSelected"?: (event: CustomEvent<string>) => void;
    }
    interface IwsGetData {
    }
    interface IntrinsicElements {
        "iws-events-finder": IwsEventsFinder;
        "iws-get-data": IwsGetData;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iws-events-finder": LocalJSX.IwsEventsFinder & JSXBase.HTMLAttributes<HTMLIwsEventsFinderElement>;
            "iws-get-data": LocalJSX.IwsGetData & JSXBase.HTMLAttributes<HTMLIwsGetDataElement>;
        }
    }
}
